spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/nvthiet1995/microservices-configserver.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "55881873984493C93AB5935A15E6C"

server:
  port: 8071